from asyncio import Semaphore

BOT_NAME = ""
DEL_LINE = "\n" + "—" * 15
DEL_LINE_END = "\n" + "—" * 15
DOT_LINE = "\n" + "·" * 45

THUMB_DEF = "https://i.postimg.cc/wTcy3zy8/default-bot-3d.png"
THUMB_ERR = "https://i.postimg.cc/tCtZ7bZG/alert-bot-3d.png"
THUMB_SEARCH = "https://i.postimg.cc/TYP54SNQ/search-bot-3d.png"

STICKER_START = "CAACAgIAAyEFAASL6tTmAAIzf2j_wnHHtX-9-eak9PxW0BHN0tYMAAJvAAPb234AAZlbUKh7k4B0NgQ"
STICKER_LOADING = "CAACAgIAAyEFAASL6tTmAAIzfWj_wfVsMSmxt5f4fRAtb5NEBcZtAAJiAAPb234AAY4XNWabE_IcNgQ"
STICKER_LOADING_DEF = "CAACAgIAAyEFAASL6tTmAAIzTGj_Vppjv_xugcDc-B0lKuBqY_A_AAJDAQACzRswCIC-idiBA72TNgQ"
STICKER_MUSIC = "CAACAgIAAxkBAAItDWj_w-mbBDRt0NWaO9G26xGCo_AWAAJnAAPb234AAT3fFO9hR5GfNgQ"
STICKER_ERROR = "CAACAgIAAxkBAAItFmj_xcF_1NliYiSUXrNmlJxoOPVPAAJjAAPb234AAYydBT3nQoPnNgQ"
STICKER_AFTER = "CAACAgIAAxkBAAItYGj_07mUpK8ZnGq7_H1DREv_4_z9AAI6AAPb234AAfOUDAtvFtSaNgQ"
STICKER_GOOD = "CAACAgIAAyEFAASL6tTmAAIzj2j_1kn9WgKaYZmBWkotFxc6JzhWAAJtAAPb234AAXUe7IXy-0SlNgQ"
STICKER_THINKS = "CAACAgIAAxkBAAItImj_x7qUWbgRVMGTxQgLnmFLItSTAAJfAAPb234AAYSwVJsRrsrjNgQ"

semaphore = Semaphore(10)